### ISSUE TITLE
use prettier

### ISSUE THREAD

**Issue by harisvsulaiman** [romgrk/node-gtk#101]
This would make code style consistent across developers.

**Comment by romgrk** [comment]
Yes :) current format is a mix of the preferences of previous authors and my personal preferences, not super consistent.

But TBH I must say I'm not a fan of prettier, it sometimes format things that I would format otherwise, e.g.:
```js
    const isMethod = ((flags & GI.FunctionInfoFlags.IS_METHOD) != 0 &&
                      (flags & GI.FunctionInfoFlags.IS_CONSTRUCTOR) == 0);
```
or
```js
const firstValue  = get.someValue("one", [1,  2, 3], kOne)
const secondValue = get.someValue("two", [0],        kTwo)
```

Those examples would be made less readable by passing them through prettier. But if other developers come around and want to setup prettier with some decent defaults I could be open to it.

**Comment by WebReflection** [comment]
I think this is the least problem of this project, at least at this stage, and styles so far weren't too crazy, IMHO

passing prettier --fix in any future, if needed, would be a no brainer

**Comment by romgrk** [comment]
Closing because there is a single maintainer for the moment.
