### ISSUE TITLE
Some take from NodeGUI project

### ISSUE THREAD

**Issue by WebReflection** [romgrk/node-gtk#129]
It looks like https://blog.atulr.com/nodegui-intro/ has the same purpose of this project but:

  * it works already in all platforms
  * it has already a React companion that simplifies a lot the UI definition

I hence wonder if:

  * it makes sense to keep maintaining this project instead of helping that one grow
  * it makes sense to have a JS library able to define with similar ease the UI

AFAIK Gtk already has its own XML representation, so it might be easier for me to target that, but I'd like to know your thoughts on this new kid in town.

Regards

**Comment by harisvsulaiman** [comment]
I prefer to use gtk and is currently building an app with this lib.

**Comment by romgrk** [comment]
Yes, Qt makes it way easier to work on all platforms no doubt on that. It's also **much** better documented than Gtk. However, I've never been a fan of their look and feel, I've never felt comfortable using it, no idea why :/

Also developing a UI solution for node is just part of the reason I work on this project. The other big reason is to learn things, so that's enough to get me going :)

**Comment by WebReflection** [comment]
fair enough, but beside keeping working on this, do you see their React porting somehow useful?

I know there is a React counter project for this library too, but I wonder if going just JS, as in no need for tooling, would be a welcomed option.

**Comment by donnisnoni95** [comment]
Yahh.. but that is Qt.... i prefer GTK...

**Comment by donnisnoni95** [comment]
> Yes, Qt makes it way easier to work on all platforms no doubt on that. It's also **much** better documented than Gtk. However, I've never been a fan of their look and feel, I've never felt comfortable using it, no idea why :/

Ya. The documentation is very well, but I don't like the look and feel too... and I don't know why too...

> Also developing a UI solution for node is just part of the reason I work on this project. The other big reason is to learn things, so that's enough to get me going :)

Agree... I like Electron too, but its more consume memory. even making a simple application, it takes up to 50MB of RAM, well indeed, because let's say we run chromium on every electron application.

I will try my best for this project.

**Comment by WebReflection** [comment]
as no answer was provided, I can close this as I see no interest in having a template tag literals based solution.
