### ISSUE TITLE
Possible wrong return value of Gtk.init on macOS

### ISSUE THREAD

**Issue by wotzlaff** [romgrk/node-gtk#231]
We found this problem after solving build issues in #230.

The problem occurs in `tests/function_call_inout.js` and `tests/conversion__array.js` (basically the same issue in both tests).
`Gtk.init(['argument1', '--gtk-debug', 'misc', 'argument2'])` returns its arguments on macOS, but should return only `['argument1', 'argument2']`.

**Comment by romgrk** [comment]
Observations:
 - Reproducible on my machine
 - Calling the `gtk_init` in C directly works as expected, the bug is on our side

**Comment by romgrk** [comment]
Ok, so after more inspection it seems that `gtk_init()` is not idempotent, which makes sense. Calling it a second time with the same arguments, right after calling it the first time, yields different results:
```
[INFO] gi.cc: InitModule: 323: first argc: 4
[INFO] gi.cc: InitModule: 325: first argc: 2
[INFO] gi.cc: InitModule: 334: second argc: 4
[INFO] gi.cc: InitModule: 336: second argc: 4
```
So my guess at this point would be that the initalization is being done by someone else before javascript's `Gtk.init(...)` has time to run. I think I will reclassify this bug as `gtk_init` doesn't work rather than in-out parameters don't work, and I'll find another in-out test case to replace this one.

**Comment by romgrk** [comment]
So I was doing a last round of debugging, I set breakpoints on all Gtk initalization functions (`gtk_init`, `gtk_init_check`, `gtk_parse_args` and `g_option_context_parse`), and I didn't find anyone else but javascript calling the Gtk init code. Then I let it run til the end. And this happened:

![Screenshot from 2020-10-29 01-13-19](https://user-images.githubusercontent.com/1423607/97528382-037f8b80-1984-11eb-987a-0c0f3711c6c4.png)

I have no idea why it suddenly starts working. It seems `gtk_init` is now being called from javascript -_-

I'm confident enough that this is a regression or change of behavior outside ourselves, also due to the fact that previous tests that ran fine months ago are now failing.

**Comment by wotzlaff** [comment]
We should definitely try to define tests which are testing only the necessary parts. It is so awful to look for functions (or methods) which have exactly the structure of in/out arguments we are trying to test. I would suggest to set up a tiny (introspected) testing library. This could be done somehow like https://github.com/GNOME/pygobject/blob/master/tests/regressextra.c for PyGObject.
The obvious question is: Does such kind of library already exists. (I mean, everyone using GIR in some other language should have similar testing problem like we do.)

If this sounds reasonable I could set up such a minimal library and implement some tests here.
