### ISSUE TITLE
Handle console warnings for invalid constant size

### ISSUE THREAD

**Issue by romgrk** [romgrk/node-gtk#234]
```
[WARN] gi.cc: GetConstantValue: 136: Couldn't load HarfBuzz.LANGUAGE_INVALID: invalid constant size: 0
```

We should either handle the case, or decide that it's acceptable that some constants have size 0. I'm not sure what that means though.

**Comment by wotzlaff** [comment]
The relevant code is here:
https://github.com/romgrk/node-gtk/blob/master/src/gi.cc#L132-L139

I would not say that it is a constant size, but rather a constant value of 0. This sounds reasonable for me to be valid.
Do you have any information about the `invalid case for Granite.options`?

**Comment by romgrk** [comment]
The documentation doesn't say anything about size 0 means value 0. Even zero values need to be stored somewhere, and that requires a size. It probably needs to be investigated further before proceeding.

**Comment by romgrk** [comment]
Here is how PyGobject handles it: https://searchcode.com/file/21308244/#l-1108

**Comment by wotzlaff** [comment]
Sorry, I misread the function call. I thought it returns the value instead of the size.
So PyGObject only sees a failure if the size is `< 0` (which is obviously bad).

It would be interesting to know how `GIArgumentToV8` handles the input with zero size. I would expect it to do the right thing anyways because the value of the `GIArgument` was set in `g_constant_info_get_value`.
