### ISSUE TITLE
Building on Windows

### ISSUE THREAD

**Issue by wotzlaff** [romgrk/node-gtk#241]
Here, I want to keep track of the current status of building the library on Windows.
The ultimate aim would be to provide a prebuilt version over npm.

What I did so far:
- Get rid of the `uname` part in `package.json` (used for `npm install` on macOS) since `uname` fails on Windows.
- Switch language to `node_js` in Travis and try to use Windows as OS.

Currently, I am facing problems with the `CALLBACK` macro which is defined in the win headers but conflicts with our enum value from `ParameterType`.

**Comment by wotzlaff** [comment]
Some more problems that could be solved are:
- fix `include`s in `bindings.gyp`
- use `guint` instead of `uint` (as the latter is not defined) - the definition in `bindings.gyp` seemed to conflict with something else
- rename `CALLBACK` and `interface` as these are predefined macros

Now I find that `g_source_add_unix_fd` in `loop.cc` is not available on Windows. Is there any possibility to get rid of this?

**Comment by romgrk** [comment]
`g_source_add_unix_fd`: let's hope. I have no idea what a replacement for that would be on windows. That part of code is where we tell GLib to use libuv's fd to check for events. UV does seem to return something on Windows ([link](https://github.com/libuv/libuv/pull/434/files)), a `HANDLE`. But I have zero idea how they epoll on Windows. This will be an interesting experience.

**Comment by romgrk** [comment]
First issue: on Windows, `uv_backend_fd()` doesn't even return a valid value. I've opened an issue on nodejs to check it it's possible to get it working in future versions. I think fom reading the past discussions it would be possible to retrieve what we want through `loop->iocp`, which is an internal private field but it "should not change".

Second issue: I'm not really sure what to do with this `HANDLE iocp` thing. We'll need to add some way for our `GSource` to get events from that thing. `g_source_add_poll(source, fd)` and the undocumented & private `g_io_channel_win32_make_pollfd` could work. I just need to find how to turn the thing into a `GIOChannel`. Otherwise if it's not possible to turn that thing into a pollable fd, I guess we'll need to make the polling ourselves using windows API.

**Comment by guesant** [comment]
>  [...] the definition in `bindings.gyp` seemed to conflict with `ffi.h`

https://github.com/romgrk/node-gtk/blob/5ae6de666fe7ba991e0ad0b11aefff6587b5024d/binding.gyp#L78

node-gtk expect libffi to be at the version 3.2.1, but MYSYS2 only stores the latest version of libffi, which is [3.3](https://packages.msys2.org/package/libffi), that probably have changed the folder structure and have included breaking changes (please see https://github.com/msys2/MSYS2-packages/issues/908 and https://github.com/msys2/MSYS2-packages/issues/908#issuecomment-678613491).

----

Somehow cgwin decided to keep the libffi version at 3.2.1 🤣 

![cgwin repo x mysys2 repo](https://user-images.githubusercontent.com/43099880/112224797-3449b100-8c02-11eb-8377-a6437e7534f6.jpg)

**Comment by ten0s** [comment]
I'm asking because I didn't see a need for it yet in the context of Gtk 3.0. User initiated events work!

**Comment by romgrk** [comment]
> I'm asking because I didn't see a need for it yet in the context of Gtk 3.0. User initiated events work!

It's been a while since I looked into it, and I've never built/used on windows so I wouldn't know :| But it's nice to hear.

The loop integration issues make things weird in edge cases; sometimes you can't cross an async-boundary because the uv loop has been essentially stopped; so simple user-clicks-callback-runs sequences are fine, but event loop callbacks aren't so fine (e.g. timers, etc).

**Comment by ten0s** [comment]
This is why I ask for some example. It's hardly possible to move forward and decide what should/shouldn't be done without one.

**Comment by romgrk** [comment]
We can close this issue as the windows build is working. For the other problems, discussion can be continued in their own issue.
