### ISSUE TITLE
Window method "inputShapeCombineRegion" dont accept Cairo argument

### ISSUE THREAD

**Issue by amunhoz** [romgrk/node-gtk#251]
I'm getting 
`TypeError: Expected argument of type cairo.Region for parameter region, got '#<CairoRegion>'`

```
const gi = require('node-gtk')
const Gtk = gi.require('Gtk', '3.0')
const Cairo = gi.require('cairo')

gi.startLoop()
Gtk.init()

const win = new Gtk.Window({ title: 'TESTE', type : Gtk.WindowType.POPUP })
win.setDefaultSize(200, 80)
win.add(new Gtk.Label({ label: 'Hello Gtk+' }))
let a  = new Cairo.Region(new Cairo.RectangleInt(10, 10, 100, 100))
win.inputShapeCombineRegion(a)  //ERROR HERE
win.showAll()
Gtk.main()

```

**Comment by romgrk** [comment]
Can reproduce, I'll try to publish a fix in the next days.

**Comment by amunhoz** [comment]
Any news?

**Comment by romgrk** [comment]
I've done some debugging in early January but ended up caugth in work & other issues and haven't been available for coding much since. I'd like to fix it soon but I don't have an ETA for now.

The root cause is that we're supplementing (incomplete) cairo GIR bindings with our own bindings, and normally it's set up so that our bindings and the GIR binding use the same function constructor instance to preserve identity. This setup is not working as intended here.

**Comment by romgrk** [comment]
This should be working now.
The patch should be in the next release that will be done when I can make the github actions workflow work (#260).
