### ISSUE TITLE
[WARN] boxed.cc: BoxedDestroyed: 229: boxed possibly not freed

### ISSUE THREAD

**Issue by stancikcom** [romgrk/node-gtk#87]
Following warning has been generated after closing example application using [X] : 
**[WARN] boxed.cc: BoxedDestroyed: 229: boxed possibly not freed**
Unfortunatelly, checking via `free` it looks like that allocated memory has not been released.
Application code:
```
const gi = require('node-gtk')
Gtk = gi.require('Gtk', '3.0')

gi.startLoop()
Gtk.init()

const win = new Gtk.Window();
win.on('destroy', () => Gtk.mainQuit())
win.on('delete-event', () => false)

win.setDefaultSize(200, 80)
win.add(new Gtk.Label({ label: 'Hello Gtk+' }))

win.showAll();
Gtk.main();

```
my configuration:
```
uname -a
Linux x230 4.15.0-43-generic #46-Ubuntu SMP Thu Dec 6 14:45:28 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
gcc --version
gcc (Ubuntu 7.3.0-27ubuntu1~18.04) 7.3.0
node --version
v10.15.0
```

**Comment by romgrk** [comment]
Yes, I'm aware of those. If I remember correctly, those are boxeds of type `GITypelib`, and are not released because of the framework. I had inspected the thing and deemed it safe to let those be de-allocated by the OS when the program exits, until I (or someone) could find more details on the correct handling of those resources.

Can you confirm that the warning appears only when the program exits, and not when a window is destroyed (in that case, it would mean we're not freeing the window)?

**Comment by romgrk** [comment]
Further tests seem to indicate other objects (KeyPressEvents) are leaked. Need to fix this.

**Comment by romgrk** [comment]
Lots of improvements have been made on memory management of boxed objects (eg Gdk.EventKey), this shouldn't be happening anymore. Re-open if it does.
